name: Build slides in CI

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt install texlive-latex-recommended texlive-latex-extra texlive-luatex make latexmk

      - name: Build slides
        run: make

      - name: Archive built PDF document
        uses: actions/upload-artifact@v4
        with:
          name: dft-slides
          path: discrete-fourier-transform.pdf
